### ISSUE TITLE
Präsentation in der kommenden Stunde

### ISSUE THREAD

**Issue by ThomasStuetz** [stefanleithenmayr/Lagerverwaltung#59]
Hallo,
aufgrund Eurer starken Aktivitäten bitte ich um Präsentation eines lauffähigen Prototypen kommenden Montag.
Danke
mfg Stütz

**Comment by stefanleithenmayr** [comment]
Sehr geehrter Herr Professor,
Präsentation am Montag passt.
MfG,
Stefan Leithenmayr
